name: Final

on: [pull_request]
                    
jobs:
    name: Task3
        runs-on: ubuntu-latest
        
        steps:
           - name: Task 
             run: echo "Ruko zara Sabar karoğŸ§ğŸ§"
